### PR TITLE
Update run.py - do not append .exe in _download_and_run()

### PR DESCRIPTION
**Pull request by Spitfire1900**
- [ ] I have added an entry to `docs/changelog.md`

## Test plan

Tested by running

```
# command(s) to exercise these changes
```

### CODE REVIEW

**Comment by chrysle** [comment]
Could you probably add logic to detect whether the application has a _.exe_ file ending or not?

**Comment by henryiii** [comment]
Assuming `.exe` is in `%PATHEXT%` (which it should always be!), then you don't need the extension to call it or to find it with [shutil.which](https://docs.python.org/3/library/shutil.html#shutil.which). If it's used other places, milage will vary, but I know those two are fine.

**Comment by Spitfire1900** [comment]
Not having '.exe' in %PATHEXT% on Windows would likely break your system, I don't think it's even appropriate to append .exe to the command call, unless we're intentionally trying to avoid overlap with a .bat somewhere.

**Comment by Spitfire1900** [comment]
FYI I'm still confused why I'm getting this, if this is reproducible on others' systems it would be a BLOCKER bug.

I will attempt to reproduce this on another Windows system before removing the draft status on this PR.

**Comment by gaborbernat** [comment]
Seems stalled, we can reopen if you pick it up again.

**Pull request closed without merging**
