### PR TITLE
Moved documentation to `docs` directory

### LINKED ISSUE #1479: Symlinks in GitHub's markdown viewer are broken
**Describe the bug**

GitHub README doesn't support linking to a symlink.
The documentation on `pipx.pypa.io` doesn't have this problem.

**How to reproduce**

Click on the link `has pre-commit support` in this example: [README@ecc06f5](https://github.com/pypa/pipx/tree/ecc06f5c9b14f075c07ba1d52aa49f43d3d7d380?tab=readme-ov-file#use-with-pre-commit)

**Expected behavior**

The `docs/installation.md` markdown file should be opened in the section `pre-commit`.

### PR DESCRIPTION
**Pull request by svengregorio**
Fixes #1479 

- [x] I have added a news fragment under `changelog.d/` (if the patch affects the end users)

## Summary of changes

Moved repository documentation in the `docs` directory, so that both GitHub's markdown viewer and the official documentation can follow links in the markdown documentation.

## Test plan

Tested by clicking on the repaired link in the [Use with pre-commit](https://github.com/pypa/pipx?tab=readme-ov-file#use-with-pre-commit) section

### CODE REVIEW

**Comment by uranusjr** [comment]
The link target is a symlink, problem is GitHub’s code viewer does not support that…

**Comment by dukecat0** [comment]
Or perhaps we can simply change it to `https://pipx.pypa.io/stable/installation/#using-pipx-with-pre-commit`?

**Comment by Gitznik** [comment]
> Or perhaps we can simply change it to `https://pipx.pypa.io/stable/installation/#using-pipx-with-pre-commit`?

This would be very confusing when looking at the docs on not `stable`. E.g. clicking the link on the `latest` docs would redirect you to the `stable` docs.

**Comment by svengregorio** [comment]
According to GitHub's [README documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes), `README.md` could be in the `docs` directory, eliminating the need for symlinks. I could whether this approach truly works in the next days.

**Comment by svengregorio** [comment]
I retroactively opened issue #1479 for this PR, I hope this doesn't cause any confusion.

**Review by chrysle — APPROVED** [review]

**Pull request merged**
