### PR TITLE
Can I be added to the volunteer list

### PR DESCRIPTION
**Pull request by Gitznik**
- [ ] I have added a news fragment under `changelog.d/` (if the patch affects the end users)

## Summary of changes

@chrysle do you care to be added as well?

## Test plan

Tested by running

```
# command(s) to exercise these changes
```

### CODE REVIEW

**Comment by chrysle** [comment]
> @chrysle do you care to be added as well?

Well, while you're at it.. ;-) I think my GH username will be enough.

**Comment by Gitznik** [comment]
> Well, while you're at it.. ;-) I think my GH username will be enough.

there you go :)

**Review by chrysle — APPROVED** [review]
Great, on further efficient collaboration!

**Comment by Gitznik** [comment]
Absolutely :muscle:

**Pull request merged**
