### PR TITLE
fix: version check for standalone python

### LINKED ISSUE #1349: Version check for standalone python is wrong.
**Describe the bug**

When specify python version to `3.1`, python 3.12 will be downloaded

**How to reproduce**

```shell
pipx install --python 3.1 --fetch-missing-python pycowsay
```

**Expected behavior**

Raise an error that no valid Python found.

### PR DESCRIPTION
**Pull request by huxuan**
- [x] I have added a news fragment under `changelog.d/` (if the patch affects the end users)

## Summary of changes

Fix #1349 

BTW, the changes also include some code refactor for related part.

## Test plan

Tested by running

```
# command(s) to exercise these changes
pipx install --python 3.1 --fetch-missing-python pycowsay
```

### CODE REVIEW

**Comment by chrysle** [comment]
Thanks for catching this. A test should be useful.

**Comment by huxuan** [comment]
> Thanks for catching this. A test should be useful.

Thanks for the review. A test cases for the issue is added, PTAL

Actually, I am not sure whether we should add such kind of tests since it is more like a hard-coding. 

I also thought to add some positive test cases but found it will make everything a little complicated to ensure the specific python version is not available especially considering tests against all python versions. If necessary, maybe we should do it in a separate pull request?

**Comment by chrysle** [comment]
> Actually, I am not sure whether we should add such kind of tests since it is more like a hard-coding.

I generally agree that adding tests that ensure certain features work as expected is a better way of coverage. However, this test case ensures an error is raised correctly on a certain occasion, thus I consider it useful.
 
> I also thought to add some positive test cases but found it will make everything a little complicated to ensure the specific python version is not available especially considering tests against all python versions and all platforms. 

It sounds reasonable to me to cover that.

**Comment by huxuan** [comment]
> > I also thought to add some positive test cases but found it will make everything a little complicated to ensure the specific python version is not available especially considering tests against all python versions and all platforms.
> 
> It sounds reasonable to me to cover that.

OK, I just forgot the usage of monkey mock and learned from other places, will add some more cases later.

**Comment by chrysle** [comment]
Thanks!

**Pull request merged**
