### PR TITLE
Add help messages for `pipx pin` and `pipx unpin` commands

### PR DESCRIPTION
**Pull request by dukecat0**
- [x] I have added a news fragment under `changelog.d/` (if the patch affects the end users)

## Summary of changes
Add help messages for `pipx pin` and `pipx unpin` commands. Currently, they're missing from the output of `pipx -h`.

## Test plan

Tested by running

```
pipx -h
```

### CODE REVIEW

**Review by chrysle — APPROVED** [review]

**Review by huxuan — APPROVED** [review]

**Comment by melutovich** [comment]
@dukecat0 Also it is unclear to me how to "pin" injected packages.  In a docker file I have:
RUN pipx install mercurial --pip-args="mercurial==6.9" && \
        pipx inject mercurial hg-git --pip-args="hg-git==1.1.4" && \
        pipx inject mercurial hg-evolve --pip-args="hg-evolve==11.1.5" && \
        pipx pin mercurial && \
        pipx pin hg-git && \
        pipx pin hg-evolve

The "pipx pin hg-git" command I believe fails
6.700 installing mercurial...
8.760 ⚠️  Note: hg was already on your PATH at /usr/bin/hg
8.762 done! ✨ 🌟 ✨
8.762   installed package mercurial 6.9, installed using Python 3.9.2
8.762   These apps are now globally available
8.762     - hg
8.967 installing hg-git...
10.20 done! ✨ 🌟 ✨
10.20   injected package hg-git into venv mercurial
10.41 installing hg-evolve...
13.31 done! ✨ 🌟 ✨
13.31   injected package hg-evolve into venv mercurial
13.71 Package hg-git is not installed

**Comment by dukecat0** [comment]
When you run `pipx pin mercurial`, all injected packages in `mercurial` are pinned as well, including `hg-git` and `hg-evolve`.

**Comment by dukecat0** [comment]
> Did this include an update to the documentation as well (I'm not seeing it there yet)?
[pipx.pypa.io/stable/docs](https://pipx.pypa.io/stable/docs/)

I haven't updated it yet, as this feature is experimental and is subject to change.

**Comment by melutovich** [comment]
> > Did this include an update to the documentation as well (I'm not seeing it there yet)?
> > [pipx.pypa.io/stable/docs](https://pipx.pypa.io/stable/docs/)
> 
> I haven't updated it yet, as this feature is experimental and is subject to change.

Ok, I was not aware that it is experimental.

**Pull request merged**
