### PR TITLE
Update packages for tests

### PR DESCRIPTION
**Pull request by meowmeowmeowcat**
* [ ] I have added an entry to `docs/changelog.md`

## Summary of changes

Update packages for tests to support Python 3.11:

* `black==20.8b1` -> `black==22.8.0`

* `https://github.com/ambv/black/archive/18.9b0.zip` -> `https://github.com/wntrblm/nox/archive/2022.1.7.zip`

* `jaraco-financial` -> `zest-releaser`

## Test plan

Tested by running
```
nox -s tests-3.11
```

### CODE REVIEW

**Comment by cs01** [comment]
Thanks! Looks good in general, but the CI tests are failing for windows and mac

**Comment by meowmeowmeowcat** [comment]
Yes, but they should pass after lxml 4.9.2 is released.

**Comment by uranusjr** [comment]
Tracking issue: https://bugs.launchpad.net/lxml/+bug/1977998

**Comment by uranusjr** [comment]
Or perhaps we could rewrite the tests to use another package instead?

**Comment by meowmeowmeowcat** [comment]
> Or perhaps we could rewrite the tests to use another package instead?

+1 on this as `jaraco-financial` has been making the CI tests on mac fail.

**Comment by meowmeowmeowcat** [comment]
However I can't find a suitable package for replacing `jaraco-financial`, so any suggestions would be appreciated!

**Comment by meowmeowmeowcat** [comment]
All tests are finally passed!

**Comment by cs01** [comment]
Thank you!

**Pull request merged**
