### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by alextremblay**
## Summary of changes
Add a note to `docs/installation.md` detailing how to install packages globally with pipx

### CODE REVIEW

**Comment by uranusjr** [comment]
Retrying CI

**Comment by uranusjr** [comment]
Oh no

```
FileNotFoundError: [WinError 206] The filename or extension is too long: 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-download-bxln6ffx\\ansible_594e68da8c6c4bef9e505074d63c37fb\\test/integration/targets/collections/collection_root_user/ansible_collections/testns/testcoll/roles/calls_intra_collection_dep_role_unqualified/meta/'
```

See also actions/setup-python#267

**Review by gaborbernat — CHANGES_REQUESTED** [review]
Merge conflicts need to be resolved.

**Comment by cs01** [comment]
I cherry-picked the commit in https://github.com/pypa/pipx/pull/814. This branch is old and has various things that make merging it difficult, so I'm just going to replace it with https://github.com/pypa/pipx/pull/814. Thank you for your contribution, and apologies for any inconvenience in the slow review.

**Pull request closed without merging**
