### PR TITLE
bump changelog to 1.4.3

### PR DESCRIPTION
**Pull request by Gitznik**
- [ ] I have added a news fragment under `changelog.d/` (if the patch affects the end users)

## Summary of changes

Bumped the changelog to 1.4.3, as the automated bump failed. @gaborbernat 

## Test plan

Tested by running

```
# command(s) to exercise these changes
```

### CODE REVIEW

**Comment by gaborbernat** [comment]
Seems readthedocs failed with this 🤔

**Comment by Gitznik** [comment]
> Seems readthedocs failed with this 🤔

Yeah looks like it does not like it if there's no news fragment. Will add a fix.

**Comment by Gitznik** [comment]
> > Seems readthedocs failed with this 🤔
> 
> Yeah looks like it does not like it if there's no news fragment. Will add a fix.

That fixed it. While looking at it I saw that the pipx inside pipx note doesn't seem to be rendered correctly. Is that expected in dev?
image

**Comment by gaborbernat** [comment]
> Is that expected?

Sounds like a bug to me.

**Comment by chrysle** [comment]
> While looking at it I saw that the pipx inside pipx note doesn't seem to be rendered correctly. Is that expected?

Let's use the [note admonition](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#usage) instead.

**Review by gaborbernat — APPROVED** [review]

**Comment by Gitznik** [comment]
> > While looking at it I saw that the pipx inside pipx note doesn't seem to be rendered correctly. Is that expected?
> 
> Let's use the [note admonition](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#usage) instead.

It already uses that: https://github.com/pypa/pipx/blob/2cf78d2c50887e222ac34d246abaad6bebe61540/docs/installation.md?plain=1#L71

**Comment by chrysle** [comment]
> It already uses that:

Oh, we're talking about different documents, then. I meant the note on the front page. The one in `installation.md` renders correctly.

**Comment by gaborbernat** [comment]
Yeah we should fix that but it sounds orthogonal to this pull request.

**Comment by Gitznik** [comment]
> > It already uses that:
> 
> Oh, we're talking about different documents, then. I meant the note on the front page. The one in `installation.md` renders correctly.

Shouldn't try to debug something while in a hurry. Thanks for clarifying. Will create a separate issue :+1:

**Pull request merged**
