### PR TITLE
add preinstall with multiple packages example, cli help and test

### PR DESCRIPTION
**Pull request by gempir**
## Summary of changes

Added examples of how to install multiple packages with preinstall. I had to dig deep into the initial PR to find out how this is supposed to be done. https://github.com/pypa/pipx/pull/900/files#r1260526621

## Test plan

Just read the docs.

### CODE REVIEW

**Review by Gitznik — APPROVED** [review]

**Comment by chrysle** [comment]
I think a newsfragment (`doc`) would be good now, too.

**Comment by gempir** [comment]
I'm sorry, I don't know what a newsfragment is. Where do I find that? What do you want me to add

**Comment by chrysle** [comment]
> I'm sorry, I don't know what a newsfragment is. Where do I find that? What do you want me to add

Take a look at our [contributing guide](https://pipx.pypa.io/stable/contributing/#changelog-entries).

**Review by chrysle — APPROVED** [review]

**Comment by chrysle** [comment]
Thanks!

**Pull request merged**
