### PR TITLE
Global install

### PR DESCRIPTION
**Pull request by vit-zikmund**
- [x] I have added an entry to `docs/changelog.md`

## Summary of changes
While `pipx` aims not to clutter the global/user python environments, the current instructions do exactly that. How about we stay clean on that front, too?

These instructions use a widely available `python3-venv` package to create a virtual environment for `pipx`, so even it stays out of the still pretty vulnerable `--user` python environment.

## Test plan

Tested by running those suggested commands :)

### CODE REVIEW

**Comment by chrysle** [comment]
This seems unnecessarily complex. I think we should remove these instructions altogether. We'll be able to suggest installing the `pipx` package via Apt with Ubuntu 24.04.

**Comment by vit-zikmund** [comment]
Well, that's already a few lines above, but most people won't be at Ubuntu 24.04 for at least a year or so. This is just an offer ;)

**Comment by maxwell-k** [comment]
I believe that pipx 1.0.0 is packaged for Ubuntu 22.04 in "universe", see https://packages.ubuntu.com/jammy/pipx

So on Ubuntu 22.04 I  follow the instructions above in the section labelled "Ubuntu 23.04 or above"

I haven't worked with Ubuntu 20.04 recently but I think there is a version of pipx available: https://packages.ubuntu.com/focal/pipx

**Comment by vit-zikmund** [comment]
Ah, interesting, there's really enough default coverage, if there's at least some `pipx` at the last supported LTS Ubuntu 20.04:
```sh
docker run --rm -it ubuntu:20.04 bash
apt update && apt install pipx
pipx --version
# 0.12.3.1
```
As the version is a tad old, I suppose the users should still be informed, that likely the latest and freshest release comes from `pip`, but then it's open for any power user to do whatever they please and we don't need to shove this admittedly complicated setup to the general public.
Thanks for the info. Closing the issue now.

**Pull request closed without merging**
