### PR TITLE
Replace pipxproject with pypa in docs and code

### PR DESCRIPTION
**Pull request by itsayellow**
* [ ] I have added an entry to `docs/changelog.md`

## Summary of changes
I grep'ed for every instance of the text `pipxproject` in the docs and code, and replaced it with `pypa`.

## Test plan

Tested by running
```
# command(s) to exercise these changes
```

### CODE REVIEW

**Comment by uranusjr** [comment]
[The documentation nav bar still shows pipx-project/pipx](https://pypa.github.io/pipx/).

image

How can this be changed, a mkdocs rebuild?

**Comment by itsayellow** [comment]
Thanks @uranusjr, yes docs need to be rebuilt.

I just manually triggered the Github workflow to rebuild the docs.  I think last night I assumed it would happen automatically, but in fact they are only rebuilt automatically for a release.

**Comment by itsayellow** [comment]
Ah nope that didn't do it.  This text is `pipx-project`, and I grep'ed for `pipxproject` and didn't catch it.  Let me fix it.

**Comment by itsayellow** [comment]
I think it's fixed now.  Thanks for the catch!

**Comment by uranusjr** [comment]
Yup, thanks!

**Pull request merged**
